id: ACBEB338C
base_file: f1501.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:56:26.695072
  last_modified_at: 2022-06-05 19:56:26.695080
