id: ACBEB338C
base_file: f5A85.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:56:26.698620
  last_modified_at: 2022-06-05 19:56:26.698627
